### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.stub.StubApp"

### ISSUE THREAD

**Issue by zxqzxq** [CuteWiseCode/apkshield#1]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.stub.StubApp" on path: DexPathList[[zip file "/data/app/~~bZGLzf0FykP4B2dQQ60XMw==/com.dn.shieldplugin-hhJ178z8-ZJy4vg8RIyAHQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~bZGLzf0FykP4B2dQQ60XMw==/com.dn.shieldplugin-hhJ178z8-ZJy4vg8RIyAHQ==/lib/arm64, /data/app/~~bZGLzf0FykP4B2dQQ60XMw==/com.dn.shieldplugin-hhJ178z8-ZJy4vg8RIyAHQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
                                                                             	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                             	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                             	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                             	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                                                                             	at androidx.core.app.CoreComponentFactory.instantiateApplication(:52)
                                                                             	at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
                                                                             	at android.app.LoadedApk.makeApplication(LoadedApk.java:1377)
                                                                             	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7060) 
                                                                             	at android.app.ActivityThread.access$1700(ActivityThread.java:275) 
                                                                             	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170) 
                                                                             	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                             	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                             	at android.os.Looper.loop(Looper.java:299) 
                                                                             	at android.app.ActivityThread.main(ActivityThread.java:8307) 
                                                                             	at java.lang.reflect.Method.invoke(Native Method) 
                                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577) 
                                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by CuteWiseCode** [comment]
已修复
